### ISSUE TITLE
Gitlab private Docker registry authentication fails

### ISSUE THREAD

**Issue by rastakajakwanna** [hashicorp/waypoint#3576]
**Describe the bug**
Waypoint keep failing to authenticate into Gitlab private Docker registry during build phase using docker-pull plugin.

**Steps to Reproduce**
Prerequisites:
* Gitlab repository
* Deploy token generated using custom user name "gitlab-sa" (https://docs.gitlab.com/ee/user/project/deploy_tokens/index.html), note that tokens are replacement of docker login password!
* Encoded auth variants:
** var1 (kubernetes format): `export GITLAB_TOKEN="put-deploy-token-here"; echo -n "{\"auths\":{\"registry.gitlab.com\":{\"auth\":\"$(echo -n "gitlab-sa:${GITLAB_TOKEN}" | base64 -w0)\"}}}" | base64 -w0`
** var2 (waypoint doc format):
```
cat << AUTH | base64 -w0
{
  "username": "gitlab-sa",
  "password": "put-token-here",
  "email": "whatever-nonsense-should-work"
}
AUTH
```

waypoint.hcl - use values from the variants above. Direct reference instead of using the file template is for simplification, all tested and neither of it worked.
```
  build {
    use "docker-pull" {
      image = "registry.gitlab.com/XY"
      tag   = var.image_tag_gitlab
      encoded_auth = xyzz # encoded values from the variants above
    }
  }
```
If that does not work, try the other supported option
```
  build {
    use "docker-pull" {
      image = "registry.gitlab.com/XY"
      tag   = var.image_tag_gitlab
      auth {
        username = "gitlab-sa"
        password = "deployment-token-here"
      }
    }
  }
```

Observe error in waypoint output
```
✓ Injecting entrypoint...
⠹ Executing Kaniko...
 │ INFO[0000] Retrieving image manifest registry.gitlab.com/XY:devel
 │ INFO[0000] Retrieving image registry.gitlab.com/XY:devel from registry registry.gitlab.com 
 │ error building image: GET https://gitlab.com/jwt/auth?scope=repository%3AXY%3Apull&service=container_regis
 │ try: DENIED: access forbidden
! exit status 1
```

Working solution which rules-out local usage by developers:
.gitlab-ci.yml job
```
waypoint-build-deploy-mr:
  image: registry.gitlab.com/gitlab-org/waypoint-images:latest
  stage: build_deploy_waypoint
  only:
    refs:
      - merge_requests
  variables:
    WAYPOINT_SERVER_ADDR: 'waypoint.my.domain:9701'
    WAYPOINT_SERVER_TOKEN: "${WAYPOINT_SERVER_TOKEN}"
    WAYPOINT_SERVER_TLS: '1'
    WAYPOINT_SERVER_TLS_SKIP_VERIFY: '1'
  services:
    - docker:dind
  script:
    - waypoint init -workspace=$CI_COMMIT_REF_SLUG
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - waypoint build
```

**Expected behavior**
Docker pull authentication works as expected.

**Waypoint Platform Versions**

* Waypoint CLI Version: v0.9.0 (2a7b89036)
* Waypoint Server Platform and Version: kubernetes, v0.9.0
* Waypoint Plugin: docker

**Additional context**
Waypoint documentation does not specify format which is expected to work.
