### ISSUE TITLE
LoadBalancer conflicting with Traefik Ingress

### ISSUE THREAD

**Issue by loic-roux-404** [hashicorp/waypoint#4585]
**Describe the bug**

```
service/waypoint-ui       LoadBalancer   10.43.228.124   <pending>     80:30590/TCP,443:31233/TCP,9701:30704/TCP,9702:30930/TCP   84s
```

Infinite pending because of : 

```
service/traefik          LoadBalancer   10.43.214.11    192.168.5.15   80:32708/TCP,443:32352/TCP   8m43s
```

How we can use correctly ingress provided in helm chart ?

I've tried next hellm chart but with no success.

**Steps to Reproduce**

In a Linux Ubuntu 22 machine

```bash
curl -sfL https://get.k3s.io | sh -
curl -Ls https://releases.hashicorp.com/waypoint/0.11.0/waypoint_0.11.0_linux_arm64.zip > /tmp/waypoint.zip
waypoint server install -platform=kubernetes -accept-tos
```

Other way is to use helm chart for acessing UI : the error is `tls: bad certificate with traefik` :
As we don't have options to trust a cert authority in the helm chart by mounting volume on cert folders inside container, i'm completly unable to setup a waypoint server with ui accessible

```yaml
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: waypoint
  namespace: kube-system
spec:
  version: 0.1.18
  chart: waypoint
  targetNamespace: default
  repo: https://helm.releases.hashicorp.com
  valuesContent: |-
    # server:
      # certs:
        # secretName: traefik-default-tls
    ui:
      service:
        type: ClusterIP
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-acme-issuer
          kubernetes.io/ingress.class: traefik
          traefik.frontend.passHostHeader: "true"
        hosts:
          - host: waypoint.k3s.test
            paths: ["/"]
        tls:
          - hosts:
              - waypoint.k3s.test
            secretName: waypoint-tls

```

**Expected behavior**
- Offer option to choose other ports for load balancer
- Provide working doc for ingress usage
- Provide a workaround with traefik internal ssl requests

**Waypoint Platform Versions**
v0.11.0

* Waypoint CLI Version: v0.11.0
* Waypoint Server Platform and Version: , kubernetes
