### ISSUE TITLE
Using Gitlab CI, unable to deploy to Cloud Run

### ISSUE THREAD

**Issue by SubatomicHero** [hashicorp/waypoint#624]
HCL

```
project = "example-nodejs"

app "example-nodejs" {
  labels = {
    "service" = "example-nodejs",
    "env"     = "dev"
  }

  path = "./src"

  build {
    use "pack" {}

    registry {
      use "docker" {
        image = "eu.gcr.io/{REDACTED_PROJECT_ID}/example-nodejs"
        tag   = "latest"
      }
    }
  }

  deploy {
    hook {
      when       = "before"
      command    = ["./activate-creds.sh"]
      on_failure = "fail"
    }

    use "google-cloud-run" {
      project  = "{REDACTED_PROJECT_ID}"
      location = "europe-west1"

      port = 5000

      static_environment = {
        "NAME" : "World"
      }

      capacity {
        memory                     = 128
        cpu_count                  = 1
        max_requests_per_container = 10
        request_timeout            = 300
      }

      auto_scaling {
        max = 2
      }
    }
  }

  release {
    use "google-cloud-run" {}
  }
}
```
.gitlab-ci.yml
```
# included docker template as we need to auth to docker and gcloud to upload image to repo
include:
  - project: platform/gitlab-ci-templates
    file: /templates/.docker-setup-template.yml
    ref: v2.6.0

stages:
  - build

.configure_waypoint:
  variables:
    APP_NAME: example-nodejs
    WAYPOINT_VERSION: '0.1.1'
    WAYPOINT_SERVER_ADDR: ''
    WAYPOINT_SERVER_TOKEN: ''
    WAYPOINT_SERVER_TLS: '1'
    WAYPOINT_SERVER_TLS_SKIP_VERIFY: '1'
  tags:
    - kube-docker

build:
  extends:
    - .setup_docker
    - .configure_waypoint
  stage: build
  services:
    - docker:dind
  script:
    - |
      # Download and install Waypoint
      # (TODO - create image that does all this and also contains docker and gcloud)
      apt-get update && apt-get install wget -y
      wget -q -O /tmp/waypoint.zip https://releases.hashicorp.com/waypoint/${WAYPOINT_VERSION}/waypoint_${WAYPOINT_VERSION}_linux_amd64.zip
      unzip -d /usr/local/bin /tmp/waypoint.zip
      rm -rf /tmp/waypoint*

      # Init the workspace
      waypoint init -workspace $CI_COMMIT_BRANCH

      # Build the artifact, based on the contents of the HCL build section
      waypoint build -workspace $CI_COMMIT_BRANCH

      # Deploy the artifact as configured in the HCL file
      waypoint deploy -workspace $CI_COMMIT_BRANCH

      # Release the artifact as configured in the HCL file
      # Different to deploy. Release makes something publicly accessible
      waypoint release -workspace $CI_COMMIT_BRANCH

      # Not able to separate out the steps as its a single action regardless of the commands
      # Could of used `waypoint up` after `waypoint init` however we may need more config options
```

The error I keep receiving is:
```
...
-> Injecting entrypoint binary to image
 Generated new Docker image: example-nodejs:latest
 -> Initializing Docker client...
 -> Tagging Docker image: example-nodejs:latest => eu.gcr.io/{REDACTED_PROJECT_ID}/example-nodejs:latest
 -> Pushing Docker image...
 The push refers to repository [eu.gcr.io/{REDACTED_PROJECT_ID}/example-nodejs]
 latest: digest: sha256:0b955387adaf938786fc142b19f04f5346e1376169452ca46b5fe23d29ae3f20 size: 2830
 -> Docker image pushed: eu.gcr.io/{REDACTED_PROJECT_ID}/example-nodejs:latest
 » Deploying...
 Activated service account credentials for: [terraform@{REDACTED_PROJECT_ID}.iam.gserviceaccount.com]
 ! Unable to list regions for project {REDACTED_PROJECT_ID}: googleapi: Error 403: Request had
   insufficient authentication scopes.
   More details:
   Reason: insufficientPermissions, Message: Insufficient Permission
```

Is it possible to see what perms are missing? I was looking through the code and couldnt see where this logs
