### ISSUE TITLE
Kubernetes service created under default namespace and not the one specified within the hcl file

### ISSUE THREAD

**Issue by cmoulliard** [hashicorp/waypoint#727]
## Issue

The kubernetes service of an application deployed is always created under the namespace `default` while the hcl config specify a different namespace

```
project = "example-java"

app "example-java" {
    build {
        use "pack" {
            builder="gcr.io/buildpacks/builder:v1"
        }
        registry {
              use "docker" {
                image = "localhost:5000/example-java"
                tag   = "latest"
                local = true
              }
            }
    }

    deploy {
      use "kubernetes" {
        namespace = "demo"
        probe_path = "/"
        service_port = 8080
      }
    }

    release {
      use "kubernetes" {
        node_port = 32000
      }
    }
}
```

## Additional information

```
kc get svc -n default
NAME           TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)        AGE
example-java   NodePort    10.96.151.154   <none>        80:32000/TCP   10m
kubernetes     ClusterIP   10.96.0.1       <none>        443/TCP        122m

kc get all -n demo
NAME                                                         READY   STATUS    RESTARTS   AGE
pod/example-java-01ent9jh09mknb6g0re9mj25wh-997cfb75-bc7xx   1/1     Running   0          10m

NAME                                                      READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/example-java-01ent9jh09mknb6g0re9mj25wh   1/1     1            1           10m

NAME                                                               DESIRED   CURRENT   READY   AGE
replicaset.apps/example-java-01ent9jh09mknb6g0re9mj25wh-997cfb75   1         1         1       10m
```

**Steps to Reproduce**
- Create a kind kubernetes cluster
- setup the server and bootstrap it
- deploy this example project - https://github.com/hashicorp/waypoint-examples/tree/main/docker/java
- Configure the hcl file with config provided here

**Investigation**
The `newService` method of the k8s release plugin dont include as parameter the `namespace` where the service should be created
see: https://github.com/hashicorp/waypoint/blob/32747c6d116bbb5815b2b395e5af2013d706ffd8/builtin/k8s/release.go#L19-L21

**Work around**
- Delete the service and re-create it under the target namespace

```
kc delete svc/example-java -n default
kubectl apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: example-java
  namespace: demo
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32000
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    name: example-java-01ent9jh09mknb6g0re9mj25wh
    waypoint.hashicorp.com/id: 01ENT9JH09MKNB6G0RE9MJ25WH
  sessionAffinity: None
  type: NodePort
EOF
```
and
```
kc port-forward --address 0.0.0.0 service/example-java 32000:80 -n demo
curl http://localhost:32000
```
