### ISSUE TITLE
Error installation on cluster that used virtual-kubelet

### ISSUE THREAD

**Issue by mataberat** [hashicorp/waypoint#852]
**Describe the bug**
I trying to set up the waypoint on Alibaba Container Service for Kubernetes (ACK). But, I face some errors when the pods are trying to create the container. It says that `virtual-kubelet/pod-controller  SDK.ServerError`.

Here's the error message from the pod description:
```
Name:           waypoint-server-0
Namespace:      waypoint
Priority:       0
Node:           <none>
Labels:         app=waypoint-server
                controller-revision-hash=waypoint-server-8678c4f6cb
                statefulset.kubernetes.io/pod-name=waypoint-server-0
Annotations:    <none>
Status:         Pending
IP:             
IPs:            <none>
Controlled By:  StatefulSet/waypoint-server
Containers:
  server:
    Image:       hashicorp/waypoint:latest
    Ports:       9701/TCP, 9702/TCP
    Host Ports:  0/TCP, 0/TCP
    Command:
      waypoint
    Args:
      server
      run
      -accept-tos
      -vvv
      -db=/data/data.db
      -listen-grpc=0.0.0.0:9701
      -listen-http=0.0.0.0:9702
    Requests:
      cpu:        100m
      memory:     256Mi
    Liveness:     http-get https://:http/ delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /data from data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-kj8t9 (ro)
Volumes:
  data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  data-waypoint-server-0
    ReadOnly:   false
  default-token-kj8t9:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-kj8t9
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                Age   From                            Message
  ----     ------                ----  ----                            -------
  Warning  ProviderInvokeFailed  61s   virtual-kubelet/pod-controller  SDK.ServerError
ErrorCode: UnknownError
Recommend: https://error-center.aliyun.com/status/search?Keyword=UnknownError&source=PopGw
RequestId: 66F746DA-3024-462C-8F90-5A27C8461B37
Message: An unknown error occurred while processing your request
  Warning  ProviderInvokeFailed  60s  virtual-kubelet/pod-controller  SDK.ServerError
```

**Steps to Reproduce**
The namespace declaration:
```
apiVersion: v1
kind: Namespace
metadata:
  name: waypoint
```
The PV declaration:
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: waypoint-server
  labels:
    alicloud-pvname: waypoint-server
    failure-domain.beta.kubernetes.io/zone: ap-southeast
    failure-domain.beta.kubernetes.io/region: ap-southeast-3
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  flexVolume:
    driver: "alicloud/disk"
    fsType: "ext4"
    options:
      volumeId: "waypoint-server"
```

The installation command:
`$ waypoint install --platform=kubernetes -accept-tos -namespace=waypoint -context-create=k8s-aliyun -context-set-default`
