### ISSUE TITLE
Ingress not working in GKE due to forced targetPort value set to "http"

### ISSUE THREAD

**Issue by dagi3d** [hashicorp/waypoint#987]
**Describe the bug**
It seems that releasing an app through Waypoint inside a GKE cluster doesn't work because of the forced service targetPort.
Although the services seems to be running correctly, if an ingress is defined, it will eventually get into an unhealthy state:

![Screen Shot 2021-01-18 at 00 02 36](https://user-images.githubusercontent.com/11283/104859951-b080f900-5920-11eb-9730-33dea698faee.png)

The problem seems to be caused by the generated service, which has assigned the `http` value for the `targetPort` field, which is translated into a 0 port value:

![Screen Shot 2021-01-18 at 00 06 21](https://user-images.githubusercontent.com/11283/104859997-05247400-5921-11eb-9e70-2e6dd03c544b.png)

Changing the service spec and overwriting the `targetPort` value, brings all the backend services into a healthy state:

![Screen Shot 2021-01-18 at 00 08 04](https://user-images.githubusercontent.com/11283/104860046-43ba2e80-5921-11eb-8675-338acd9c48b7.png)

![Screen Shot 2021-01-18 at 00 10 22](https://user-images.githubusercontent.com/11283/104860119-aca1a680-5921-11eb-9c0a-62c91da65edf.png)

The problem is this value will be reseted to the `http` value after each Waypoint release.

Maybe I am missing something as it seems to work out of the box in a minikube cluster, but not in GKE.
Happy to patch the kubernetes plugin to allow to set any arbitrary value for the `targetPort` field if it makes sense.

**Steps to Reproduce**
Having the correct kube config pointing to your GKE cluster and having Waypoint installed on it, submit the following app:

```
project = "test"

app "hello-world" {
  build {
    use "docker-pull" {
      image = "heroku/nodejs-hello-world"
      tag = "latest"
    }
  }

  deploy {
    use "kubernetes" {
        service_port=5000
    }
  }

  release {
    use "kubernetes" {
      port=5000
    }
  }

  url {
    auto_hostname = false
  }
}
```
```
waypoint init
waypoint up
```

Add the following ingress in your GKE cluster:

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-hello-world
spec:
  rules:
  - host: "hello-world.test"
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-world
          servicePort: 5000
```

Once the ingress is created, one of the backend services will be go from UNKOWN state to UNHEALTHY
Change the `hello-world` service YAML inside the GKE console and the ingress backend services will change to OK
